### ISSUE TITLE
Guidance building an example JS app 

### ISSUE THREAD

**Issue by highfiiv** [buttplugio/buttplug-rs-ffi#31]
**Feature Description**
I’ve read most of the public info on inteface and syncydync but am stil perplexed by how to develop with it. I’m currently working in Angular and would love to build out some example components which send static and dynamic messages to inteface for controlling Lovense devices.

Would @qdot be willing to answer questions regarding standard connectivity and communication from the JS app?

I have a few ideas I’d like to build out and would give the work to your community of course.

Clear definition of the feature, possibly including any help you could provide on implementing this feature, or resources you would need help with implementation.

**Comment by qdot** [comment]
You are just *ever* so slightly ahead of me right now. I'm working on rewriting the developer guide as we speak, which will cover a lot of these topics. The new version is at

https://dev.buttplug-developer-guide.docs.buttplug.io

I'm just now getting to the "Writing applications" part, which will use the new FFI layer.

Also, I'll say up front that figuring out how to get the WASM stuff to play nicely with webpack is still in a work in progress. I'm porting my own web apps (playground and syncydink) to buttplug-wasm right now in order to iron this out a bit, but it may take some work.

Anyways, yeah, happy to answer questions. Can do it here, though usually it's easier on our discord server: https://discord.buttplug.io

**Comment by highfiiv** [comment]
@qdot thanks for your reply. I have no experience with WASM but perhaps it can interface with native JS as a layer above it?

I've replied on [Discord](https://discord.com/channels/353303527587708932/377916908764266499/779479557505679362)

**Comment by qdot** [comment]
Closing 'cause it's mostly going to be taken care of via documentation.
